# Generated by Django 5.0.6 on 2024-05-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="view_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите колличество просмотров",
                verbose_name="Счетчик просмотров",
            ),
        ),
    ]
